frr version 10.0
frr defaults traditional
hostname spine-01
service integrated-vtysh-config
log syslog informational
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.0.11.3 remote-as 65101
 neighbor 10.0.12.3 remote-as 65102
 !
 address-family ipv4 unicast
  neighbor 10.0.11.3 activate
  neighbor 10.0.12.3 activate
 exit-address-family
!
line vty
