frr version 10.0
frr defaults traditional
hostname leaf-02
service integrated-vtysh-config
log syslog informational
!
router bgp 65102
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.12.2 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 10.0.12.2 activate
 exit-address-family
!
line vty
