frr version 10.0
frr defaults traditional
hostname isolated-01
service integrated-vtysh-config
log syslog informational
!
router bgp 65200
 bgp router-id 2.2.2.3
 no bgp ebgp-requires-policy
 !
 address-family ipv4 unicast
 exit-address-family
!
line vty
